### ISSUE TITLE
has no method 'set'

### ISSUE THREAD

**Issue by bellwood** [geekuillaume/Node.js-Chat#7]
When you enter a name and submit the form you see:

[root@dev nodejs]# node server.js
Server listening on port 80
Warning: missing space before text for line 52 of jade file "/home/nodejs/views/home.jade"
Warning: missing space before text for line 54 of jade file "/home/nodejs/views/home.jade"
Warning: missing space before text for line 59 of jade file "/home/nodejs/views/home.jade"
Warning: missing space before text for line 66 of jade file "/home/nodejs/views/home.jade"
Warning: missing space before text for line 67 of jade file "/home/nodejs/views/home.jade"

/home/nodejs/server.js:56
        socket.set('pseudo', data, function(){
               ^
TypeError: Object #<Socket> has no method 'set'
    at Socket.<anonymous> (/home/nodejs/server.js:56:11)
    at Socket.emit (events.js:95:17)
    at Socket.onevent (/home/nodejs/node_modules/socket.io/lib/socket.js:326:8)
    at Socket.onpacket (/home/nodejs/node_modules/socket.io/lib/socket.js:286:12)
    at Client.ondecoded (/home/nodejs/node_modules/socket.io/lib/client.js:181:14)
    at Decoder.Emitter.emit (/home/nodejs/node_modules/socket.io/node_modules/socket.io-parser/node_modules/emitter/index.js:132:20)
    at Decoder.add (/home/nodejs/node_modules/socket.io/node_modules/socket.io-parser/index.js:233:12)
    at Client.ondata (/home/nodejs/node_modules/socket.io/lib/client.js:166:16)
    at Socket.emit (events.js:95:17)
    at Socket.onPacket (/home/nodejs/node_modules/socket.io/node_modules/engine.io/lib/socket.js:96:14)

**Comment by krisdahl** [comment]
Looks to me like this app has very specific (older) needs for socket.io as well as express, but is set in package.json to use latest versions...
